#!/usr/bin/perl
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
#
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# This script is meant to use with i3blocks. It parses the output of the "acpi"
# command (often provided by a package of the same name) to read the status of
# the battery, and eventually its remaining time (to full charge or discharge).
#
# The color will gradually change for a percentage below 85%, and the urgency
# (exit code 33) is set if there is less that 5% remaining.

use strict;
use warnings;
use utf8;

my $acpi_bat0;
my $acpi_bat1;
my $status0;
my $status1;
my $percent0;
my $percent1;
my $full_text0;
my $full_text1;
my $short_text0;
my $short_text1;
my $bat0_number = 0;
my $bat1_number = 1;

# read the first line of the "acpi" command output
open (ACPI, "acpi -b | grep 'Battery $bat0_number' |") or die;
$acpi_bat0 = <ACPI>;
open (ACPI, "acpi -b | grep 'Battery $bat1_number' |") or die;
$acpi_bat1 = <ACPI>;
close(ACPI);

# fail on unexpected output
if ($acpi_bat0 !~ /: (\w+), (\d+)%/) {
	die "$acpi_bat0\n";
}

$status0 = $1;
$percent0 = $2;
$full_text0 = "$percent0%";

if ($acpi_bat1 !~ /: (\w+), (\d+)%/) {
	die "$acpi_bat1\n";
}

$status1 = $1;
$percent1 = $2;
$full_text1 = "$percent1%";

if ($status0 eq 'Discharging') {
	$full_text0.= ' DIS';
} elsif ($status0 eq 'Charging') {
	$full_text0.= ' CHR';
} elsif ($status0 eq 'Unknown') {
	$full_text0.= ' OFF';
}

if ($status1 eq 'Discharging') {
        $full_text1.= ' DIS';
} elsif ($status1 eq 'Charging') {
        $full_text1.= ' CHR';
} elsif ($status1 eq 'Unknown') {
        $full_text1.= ' OFF';
}


$short_text0 = $full_text0;
$short_text1 = $full_text1;

if ($acpi_bat0 =~ /(\d\d:\d\d):/) {
	$full_text0 .= " ($1)";
}

if ($acpi_bat1 =~ /(\d\d:\d\d):/) {
	$full_text1 .= " ($1)";
}

# print text
print "$full_text0  $full_text1\n";
print "$short_text0  $short_text1";

# consider color and urgent flag only on discharge
if ($status0 eq 'Discharging') {

	if ($percent0 + $percent1 < 20) {
		print "#FF0000\n";
	} elsif ($percent0 + $percent1 < 40) {
		print "#FFAE00\n";
	} elsif ($percent0 + $percent1 < 60) {
		print "#FFF600\n";
	} elsif ($percent0 + $percent1 < 85) {
		print "#A8FF00\n";
	}

	if ($percent0 + $percent1 < 5) {
		exit(33);
	}
}

exit(0);
