#!/bin/bash

if [ $# -eq 0 ]; then
    cat /proc/acpi/ibm/fan | grep -v command
    exit 1
fi

key=$1

if (($key < 2))
then
	echo "level 0" | sudo tee /proc/acpi/ibm/fan
elif (($key < 4))
then	
	echo "level 2" | sudo tee /proc/acpi/ibm/fan
elif (($key < 6))
then
	echo "level 4" | sudo tee /proc/acpi/ibm/fan
elif (($key < 8))
then
	echo "level 7" | sudo tee /proc/acpi/ibm/fan
else
	echo "level auto" | sudo tee /proc/acpi/ibm/fan
fi
